### ISSUE TITLE
Status code 400 when calling NexmoClient.getVoiceClient().ModifyCall()

### ISSUE THREAD

**Issue by Fleta** [Vonage/vonage-java-sdk#274]
1. What I did
- NexmoClient.getVoiceClient().modifyCall(uuid, MidfyCallAction.HANGUP)
- checked https://developer.nexmo.com/api/voice#updateCall 

2. Result (Stacktrace except which I implemented)
```
com.nexmo.client.NexmoResponseParseException: Unable to parse response.
	at com.nexmo.client.AbstractMethod.execute(AbstractMethod.java:107)
	at com.nexmo.client.voice.CallsEndpoint.put(CallsEndpoint.java:101)
	at com.nexmo.client.voice.VoiceClient.modifyCall(VoiceClient.java:169)
	at com.nexmo.client.voice.VoiceClient.modifyCall(VoiceClient.java:152)
	at MYPACKAGE$MYCLASS(MYCLASS:line)
	at MYPACKAGE$MYCLASS(MYCLASS:line)
	at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:22)
	at io.javalin.http.JavalinServlet$addHandler$protectedHandler$1.handle(JavalinServlet.kt:116)
	at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:45)
	at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:24)
	at io.javalin.http.JavalinServlet$service$1.invoke(JavalinServlet.kt:123)
	at io.javalin.http.JavalinServlet$service$2.invoke(JavalinServlet.kt:40)
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:75)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:544)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at io.javalin.core.JavalinServer$start$httpHandler$1.doHandle(JavalinServer.kt:53)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:494)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.client.HttpResponseException: status code: 400, reason phrase: Bad Request
	at org.apache.http.impl.client.AbstractResponseHandler.handleResponse(AbstractResponseHandler.java:70)
	at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:66)
	at com.nexmo.client.voice.ModifyCallMethod.parseResponse(ModifyCallMethod.java:65)
	at com.nexmo.client.voice.ModifyCallMethod.parseResponse(ModifyCallMethod.java:38)
	at com.nexmo.client.AbstractMethod.execute(AbstractMethod.java:103)
	... 37 more
```

3. How to reproduce
Call `NexmoClient.getVoiceClient().modifyCall(String uuid, ModifyCallAction action)`

Thanks for your efforts.

**Comment by vinokanth92** [comment]
Come on guys any update on this? @cr0wst

**Comment by yallen011** [comment]
Relates to #294
