### ISSUE TITLE
    java.lang.NoSuchFieldError: No field DEF_CONTENT_CHARSET of type Ljava/nio/charset/Charset; in class Lorg/apache/http/protocol/HTTP; or its superclasses (declaration of 'org.apache.http.protocol.HTTP' appears in /system/framework/org.apache.http.legacy.boot.jar)

### ISSUE THREAD

**Issue by abdelkawi** [Vonage/vonage-java-sdk#282]
i got this error 

Error log
at org.apache.http.client.methods.RequestBuilder.build(RequestBuilder.java:464)
        at com.nexmo.client.AbstractMethod.execute(AbstractMethod.java:79)
        at com.nexmo.client.verify.VerifyEndpoint.verify(VerifyEndpoint.java:53)
        at com.nexmo.client.verify.VerifyEndpoint.verify(VerifyEndpoint.java:49)
        at com.nexmo.client.verify.VerifyClient.verify(VerifyClient.java:73)
        at com.example.pincodeview.MainActivity.onCreate(MainActivity.kt:25)
        at android.app.Activity.performCreate(Activity.java:6915)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by slorello89** [comment]
Hi @abdelkawi 

I'm afraid we don't support running the Java server SDK on android as you would have to distribute your Nexmo API key and secret in order to run it (which is a security risk). This appears to be what's causing the conflict between the HttpClient's which is the root cause of this exception. If you'd like to use the Nexmo Java server SDK you will need to use it Server Side.
